In [48]:

import os
import pandas as pd

json_file_path = os.path.join("..", "inventory", "inventory.json")

inventory = pd.read_json(json_file_path)   

inventory.head()

,name,category,price,specs,description
0,TravelBook 14,laptop,28999,"{'weight_kg': 1.4, 'ram_gb': 16, 'storage_gb':...","Lightweight laptop for travel, coding and ever..."
1,CodePro 15,laptop,29999,"{'weight_kg': 1.8, 'ram_gb': 16, 'storage_gb':...",Performance-focused laptop suitable for progra...
2,PowerMax 15,laptop,34999,"{'weight_kg': 2.1, 'ram_gb': 16, 'storage_gb':...",High-performance laptop for development and de...
3,LiteBook 13,laptop,26999,"{'weight_kg': 1.2, 'ram_gb': 8, 'storage_gb': ...",Ultra-light laptop with excellent battery life...
4,BudgetBook 14,laptop,21999,"{'weight_kg': 1.7000000000000002, 'ram_gb': 8,...",Affordable laptop for basic productivity and e...

In [49]:
print(inventory.head())
print(inventory.columns)
print(inventory.dtypes)

            name category  price  \
0  TravelBook 14   laptop  28999
1     CodePro 15   laptop  29999
2    PowerMax 15   laptop  34999
3    LiteBook 13   laptop  26999
4  BudgetBook 14   laptop  21999

                                               specs  \
0  {'weight_kg': 1.4, 'ram_gb': 16, 'storage_gb':...
1  {'weight_kg': 1.8, 'ram_gb': 16, 'storage_gb':...
2  {'weight_kg': 2.1, 'ram_gb': 16, 'storage_gb':...
3  {'weight_kg': 1.2, 'ram_gb': 8, 'storage_gb': ...
4  {'weight_kg': 1.7000000000000002, 'ram_gb': 8,...

                                         description
0  Lightweight laptop for travel, coding and ever...
1  Performance-focused laptop suitable for progra...
2  High-performance laptop for development and de...
3  Ultra-light laptop with excellent battery life...
4  Affordable laptop for basic productivity and e...
Index(['name', 'category', 'price', 'specs', 'description'], dtype='str')
name              str
category          str
price           int64
specs          object
description       str
dtype: object

In [50]:
specs = pd.json_normalize(inventory["specs"])
print(specs)
inventory = pd.concat(
    [inventory.drop(columns=["specs"]), specs],
    axis=1
)
print(inventory.head())

    weight_kg  ram_gb  storage_gb  battery_hours      processor
0         1.4      16         512              9  Intel Core i5
1         1.8      16         512              7    AMD Ryzen 5
2         2.1      16        1024              8  Intel Core i7
3         1.2       8         512             11  Intel Core i3
4         1.7       8         256              6    AMD Ryzen 3
5         2.3      32        1024              7  Intel Core i7
6         1.5      16         512             12    AMD Ryzen 5
7         2.4      16        1024              5    AMD Ryzen 7
8         1.6       8         256              8  Intel Core i3
9         1.9      32        1024              8  Intel Core i7
10        1.1      16         512             13  Intel Core i5
11        1.9      16         512              8    AMD Ryzen 5
12        1.3      16         512             10  Intel Core i5
13        1.8       8         256              7  Intel Core i3
14        1.9      32         512              9    AMD Ryzen 7
15        1.3      16         512             12    AMD Ryzen 5
16        2.0       8         512              7  Intel Core i5
17        1.5      16         512             10    AMD Ryzen 5
            name category  price  \
0  TravelBook 14   laptop  28999
1     CodePro 15   laptop  29999
2    PowerMax 15   laptop  34999
3    LiteBook 13   laptop  26999
4  BudgetBook 14   laptop  21999

                                         description  weight_kg  ram_gb  \
0  Lightweight laptop for travel, coding and ever...        1.4      16
1  Performance-focused laptop suitable for progra...        1.8      16
2  High-performance laptop for development and de...        2.1      16
3  Ultra-light laptop with excellent battery life...        1.2       8
4  Affordable laptop for basic productivity and e...        1.7       8

   storage_gb  battery_hours      processor
0         512              9  Intel Core i5
1         512              7    AMD Ryzen 5
2        1024              8  Intel Core i7
3         512             11  Intel Core i3
4         256              6    AMD Ryzen 3

In [ ]:
user_requirements = {
    "weight_kg": 1.5,
    "ram_gb": 8,
    "storage_gb": 256,
    "battery_hours": 8
}

In [ ]:
matching_products = inventory[
    (inventory["weight_kg"] <= user_requirements["max_weight_kg"]) &
    (inventory["ram_gb"] >= user_requirements["min_ram_gb"]) &
    (inventory["storage_gb"] >= user_requirements["min_storage_gb"]) &
    (inventory["battery_hours"] >= user_requirements["min_battery_hours"])
]

In [58]:
matching_products

,name,category,price,description,weight_kg,ram_gb,storage_gb,battery_hours,processor
0,TravelBook 14,laptop,28999,"Lightweight laptop for travel, coding and ever...",1.4,16,512,9,Intel Core i5
3,LiteBook 13,laptop,26999,Ultra-light laptop with excellent battery life...,1.2,8,512,11,Intel Core i3
6,EcoLaptop 14,laptop,31999,Energy-efficient laptop with long battery life...,1.5,16,512,12,AMD Ryzen 5
10,UltraLite 13,laptop,37999,Premium ultra-light laptop focused on portabil...,1.1,16,512,13,Intel Core i5
12,PixelBook 14,laptop,30999,Portable laptop with a strong balance of perfo...,1.3,16,512,10,Intel Core i5
15,RoadWarrior 14,laptop,32999,Travel-friendly laptop designed for long worki...,1.3,16,512,12,AMD Ryzen 5
17,FlexiBook 14,laptop,29999,"Balanced laptop offering portability, performa...",1.5,16,512,10,AMD Ryzen 5